-- Analysis Queries

-- TOTAL NUMBER OF TRIPS IN THE COLLECTED DATA
SELECT COUNT(DISTINCT TRIP_ID) FROM GTFS.TRIP_UPDATES;

-- TOTAL NUMBER OF TRIPS PER MODE OF TRANSPORT SELECTED
SELECT ROUTE_SHORT_NAME, 
CASE ROUTE_TYPE 
WHEN '0' THEN 'TRAM'
WHEN '1' THEN 'SUBWAY'
WHEN '2' THEN 'RAIL'
WHEN '3' THEN 'BUS'
WHEN '4' THEN 'FERRY'
END AS ROUTE_TYPE, 
COUNT(DISTINCT TRIP_ID)
FROM GTFS.TRIP_UPDATES
GROUP BY ROUTE_SHORT_NAME
ORDER BY ROUTE_SHORT_NAME;

-- FIND TRIP DATA FOR MAX ARRIVAL DELAY
SELECT * FROM GTFS.TRIP_UPDATES 
WHERE TRIP_ID IN ( SELECT DISTINCT TRIP_ID
FROM GTFS.TRIP_UPDATES
WHERE ARRIVAL_DELAY = (SELECT MAX(ARRIVAL_DELAY) FROM GTFS.TRIP_UPDATES))
ORDER BY TRIP_ID, STOP_SEQUENCE, FETCH_TIME;

-- FIND TRIP DATA FOR MIN ARRIVAL DELAY
SELECT TU.*, S.STOP_NAME, STOP_LAT, STOP_LON
FROM GTFS.TRIP_UPDATES TU, GTFS.STOPS S
WHERE TRIP_ID IN (SELECT DISTINCT TRIP_ID
FROM GTFS.TRIP_UPDATES
WHERE ARRIVAL_DELAY = (SELECT MIN(ARRIVAL_DELAY) FROM GTFS.TRIP_UPDATES))
AND TU.STOP_ID = S.STOP_ID
ORDER BY STOP_SEQUENCE, FETCH_TIME;

SELECT COUNT(DISTINCT ROUTE_ID) FROM GTFS.TRIP_UPDATES;

-- FIND MAPPING BETWEEN STOP_SEQUENCE AND STOP_ID
SELECT TRIP_ID, STOP_ID, COUNT(DISTINCT STOP_SEQUENCE)
FROM GTFS.TRIP_UPDATES
-- WHERE TRIP_ID = '84384099'-- 
GROUP BY TRIP_ID, STOP_ID
ORDER BY TRIP_ID, STOP_ID;

-- FIND A RANDOM TRIP

SELECT * FROM GTFS.TRIP_UPDATES WHERE fetch_time < start_time order by trip_id, stop_sequence;

SELECT *, date_sub(start_time, INTERVAL 1 SECOND) FROM GTFS.TRIP_UPDATES WHERE TRIP_ID = '82665245' order by trip_id, stop_sequence, fetch_time;

SELECT TIME_TO_SEC(TIMEDIFF(TIME(FETCH_TIME), TIME(START_TIME))), TIME(FETCH_TIME), TIME(START_TIME), TIME(FETCH_TIME) - TIME(START_TIME), TIME(START_TIME) - TIME(FETCH_TIME), trip_updates.* 
FROM GTFS.TRIP_UPDATES WHERE TRIP_ID = '82665245' ORDER BY TRIP_ID, STOP_SEQUENCE, FETCH_TIME;

SELECT TU.*, TIME_TO_SEC(TIMEDIFF(TIME(TU.FETCH_TIME), TIME(TU.START_TIME))), S.STOP_NAME, S.STOP_LAT, S.STOP_LON
FROM GTFS.TRIP_UPDATES TU, GTFS.STOPS S
WHERE TRIP_ID = '82665245' 
AND TU.STOP_ID = S.STOP_ID
ORDER BY STOP_SEQUENCE, FETCH_TIME;

-- DISTINCT TRIP COUNT BY STOP
SELECT S.STOP_ID, S.STOP_NAME, COUNT(DISTINCT TRIP_ID)
FROM GTFS.TRIP_UPDATES TU, GTFS.STOPS S
WHERE TU.STOP_ID = S.STOP_ID
AND UPPER(S.STOP_NAME) LIKE '%AMSTERDAM,%'
GROUP BY S.STOP_ID
ORDER BY S.STOP_NAME;

SELECT S.STOP_ID, S.STOP_NAME, COUNT(DISTINCT TRIP_ID)
FROM GTFS.STOP_TIMES ST, GTFS.STOPS S
WHERE ST.STOP_ID = S.STOP_ID
AND UPPER(S.STOP_NAME) LIKE '%AMSTERDAM,%'
GROUP BY S.STOP_ID
ORDER BY S.STOP_NAME;

-- HEATMAP MAYBE?
SELECT STOP_ID, TRIP_ID, MAX(ARRIVAL_DELAY), MIN(ARRIVAL_DELAY), AVG(ARRIVAL_DELAY), MAX(DEPARTURE_DELAY), MIN(DEPARTURE_DELAY), AVG(DEPARTURE_DELAY)
FROM GTFS.TRIP_UPDATES
GROUP BY STOP_ID, TRIP_ID;