-- USE GTFS;

-- CREATE INDEX trip_updates__trip_id
-- ON trip_updates(trip_id);

-- CREATE INDEX trip_updates__stop_id
-- ON trip_updates(stop_id);

-- CREATE INDEX trip_updates__arrival_delay
-- ON trip_updates(arrival_delay);

-- CREATE INDEX trip_updates__departure_delay
-- ON trip_updates(departure_delay);

-- CREATE INDEX trip_updates__start_date
-- ON trip_updates(start_date);

-- CREATE INDEX trip_updates__route_id
-- ON trip_updates(route_id);

-- CREATE INDEX trip_updates__fetch_time
-- ON trip_updates(fetch_time);

-- ALTER TABLE GTFS.TRIP_UPDATES DROP INDEX trip_updates__route_id;

SELECT MIN(FETCH_TIME) FROM GTFS.TRIP_UPDATES WHERE FETCH_TIME >= '2019-02-11 09:30:00';

SELECT MIN(FETCH_TIME) FROM GTFS.TRIP_UPDATES WHERE FETCH_TIME >= '2019-02-15 14:30:00';

SELECT COUNT(1) FROM GTFS.TRIP_UPDATES;

SELECT DATE(FETCH_TIME), COUNT(1) FROM GTFS.TRIP_UPDATES GROUP BY DATE(FETCH_TIME);

SELECT ROUTE_ID, COUNT(DISTINCT TRIP_ID) FROM GTFS.TRIP_UPDATES GROUP BY ROUTE_ID;

SELECT ROUTE_ID, COUNT(DISTINCT STOP_ID) FROM GTFS.TRIP_UPDATES WHERE FETCH_TIME >= '2019-02-11' AND START_DATE <> '20190211' GROUP BY ROUTE_ID;

SELECT START_DATE, COUNT(DISTINCT TRIP_ID) FROM GTFS.TRIP_UPDATES 
GROUP BY START_DATE;

SELECT * FROM GTFS.TRIP_UPDATES WHERE FETCH_TIME > '2019-02-11' ORDER BY FETCH_TIME;

--

SELECT * FROM GTFS.ROUTES WHERE AGENCY_ID = 'GVB' AND ROUTE_SHORT_NAME IN ('907', '901', '22', '281', '4', '24', '54', '51');

SELECT DISTINCT(START_DATE) FROM GTFS.TRIP_UPDATES WHERE ROUTE_ID = '61617' AND FETCH_TIME >= '2019-02-10' AND START_DATE <> '20190210';

SELECT * FROM GTFS.TRIP_UPDATES WHERE ROUTE_ID = '61617' AND FETCH_TIME >= '2019-02-11' AND START_DATE <> '20190211' ORDER BY FETCH_TIME;

SELECT DISTINCT STOP_ID FROM GTFS.TRIP_UPDATES WHERE ROUTE_ID = '61617' AND FETCH_TIME >= '2019-02-11' AND START_DATE <> '20190211';

SELECT * FROM GTFS.TRIP_UPDATES WHERE ROUTE_ID = '60668' AND FETCH_TIME >= '2019-02-11' AND START_DATE <> '20190211' ORDER BY FETCH_TIME;

SELECT * FROM GTFS.TRIP_UPDATES WHERE TRIP_ID = '86197074' ORDER BY FETCH_TIME, STOP_SEQUENCE;

-- NIGHT BUS AVG DELAY ACROSS STOPS
SELECT STOP_ID, AVG(ARRIVAL_DELAY), AVG(DEPARTURE_DELAY) FROM GTFS.TRIP_UPDATES 
WHERE ROUTE_ID = '60668' AND FETCH_TIME >= '2019-02-11' AND START_DATE <> '20190211' GROUP BY STOP_ID;

-- AVG DELAY ACROSS STOPS FOR ALL OTHER LINES
SELECT ROUTE_ID, STOP_ID, AVG(ARRIVAL_DELAY), AVG(DEPARTURE_DELAY) FROM GTFS.TRIP_UPDATES 
WHERE ROUTE_ID <> '60668' AND FETCH_TIME >= '2019-02-11' AND START_DATE <> '20190211' AND START_DATE <> '20190219'
GROUP BY ROUTE_ID, STOP_ID ORDER BY ROUTE_ID;